### ISSUE TITLE
Add github actions to the templates

### ISSUE THREAD

**Issue by jmsmkn** [comic/evalutils#260]
It would be nice if the generated repo for processors and evaluations would have a github actions file that would run the tests for the user, adding CI automatically.

**Comment by silvandeleemput** [comment]
@jmsmkn Since we have now merged #263, can we close this?

**Comment by jmsmkn** [comment]
We need to test it with a templated processor and add documentation about how to set it up, I will do this.

**Comment by jmsmkn** [comment]
Done
