### ISSUE TITLE
Suggestions for CLI improvements

### ISSUE THREAD

**Issue by jmsmkn** [comic/evalutils#261]
The CLI is a little confusing right now and I cannot get it to work for a processor:

- Why are some arguments on the CLI and some gathered via cookie cutter, this should be consistent
- No early validation of the project name, you have to fill everything out first
- The top level verbs for evalutils are ugly, processor or evaluator should be an argument

**Comment by jmsmkn** [comment]
- Add .gitattributes file and instructions about how to set up git lfs, we have enough free storage on github.com/DIAGNijmegen

**Comment by jmsmkn** [comment]
Weird, the github automation did not work. Maybe put the keyword on a new line?

**Comment by silvandeleemput** [comment]
> Weird, the github automation did not work. Maybe put the keyword on a new line?

How did you test this? Did you create a new project/repo using the template? Shall we open a new issue for this?

**Comment by jmsmkn** [comment]
> > Weird, the github automation did not work. Maybe put the keyword on a new line?
> 
> How did you test this? Did you create a new project/repo using the template? Shall we open a new issue for this?

No, I mean the automation from the PR. The line in https://github.com/comic/evalutils/pull/270#issue-370049741

> This PR closes #261

Didn't actually close #261. I think you have to put them on separate lines, eg, https://github.com/comic/grand-challenge.org/pull/1098#issue-363742923
