### ISSUE TITLE
Improve parsing of exceptions from ITK

### ISSUE THREAD

**Issue by jmsmkn** [comic/evalutils#298]
The exception messages from itk are now multiline, which result in unintelligible error messages when they're passed to grand challenge (see https://covid-segmentation.grand-challenge.org/FAQs/). These should be handled better.

**Comment by silvandeleemput** [comment]
I created some error catching methods specifically for SimpleITK (bodyct-multiview-nodule-detection), we could potentially use those to catch and reformat the SimpleITK exceptions

 https://github.com/DIAGNijmegen/bodyct-multiview-nodule-detection/pull/95

**Comment by jmsmkn** [comment]
This is no longer relevant as image loading is no longer handled by evalutils.
