### ISSUE TITLE
Test suite for algorithm containers

### ISSUE THREAD

**Issue by kiranvaidhya** [comic/evalutils#310]
When `./test.sh` is called, the following error is encountered often:

```
Could not load expected_output.json using <evalutils.io.SimpleITKLoader object at 0x7f70508d6310>.
```
This suggests that evalutils is reading all the files from the automatically-generated `test/` folder. 
`expected_output.json` should be ignored from the `test/` folder, and there should be a way to build an automatic test suite.

**Comment by jmsmkn** [comment]
#260

**Comment by IshanMohanty** [comment]
I'm facing the same problem while executing the test.sh script. This is for the MIDOG challenge 2022. 
Link to the MIDOG reference docker i refered: [MIDOG_2022](https://github.com/DeepPathology/MIDOG_reference_docker/tree/6bdd60294828a1166a819951ba7aa4cb18da7352)

**Comment by jmsmkn** [comment]
Templating will be removed from this repo as that has moved to https://github.com/DIAGNijmegen/rse-grand-challenge-forge.
