### ISSUE TITLE
Parameter specification not working for `evalutils init algorithm`

### ISSUE THREAD

**Issue by joeranbosma** [comic/evalutils#318]
* evalutils version: 0.2.4
* Python version: 3.8.5
* Operating System: macOS (also tested with WLS2 on Windows 11)

### Description

The questionnaire when initializing an algorithm with evalutils is broken. Instead of asking for the required inputs, it throws an error. This happens for the number of op CPUs and GPUs. I have tested this on both macOS and WSL2 on Windows 11, and the error messages were exactly the same. 

If possible, it would be amazing if this issue would be fixed before the Algorithm workshop on 19 October 2021. 

### What I Did

```
evalutils init algorithm VesselSegmentationContainer
> Segmentation (but same error persists for Detection/Classification)
```

![image](https://user-images.githubusercontent.com/5995183/136511967-483a7587-afc8-480c-b4b8-92e13971eb25.png)

This issue can be circumvented by adding the flag manually. Doing so yields a similar issue with the number of GPUs:
![image](https://user-images.githubusercontent.com/5995183/136512024-a0a06210-965c-42d5-91f3-4210b7bb36cf.png)

Also, shouldn’t it be possible to have an algorithm that does not require a GPU?
Adding that flag as well results in a different order of questions, but it succeeds in the end: 
![image](https://user-images.githubusercontent.com/5995183/136512164-70fe2d7f-f1a5-4fc0-8c30-226bf40ead1d.png)

**Comment by jmsmkn** [comment]
Most of (if not all) these options were removed in https://github.com/comic/evalutils/commit/fd791e0f1715d78b3766ac613371c447607e411d - can you check to see if this is an issue on master?
