### ISSUE TITLE
Github CI - running the test.sh script (run from ci.yml) runs infinitely

### ISSUE THREAD

**Issue by GabyRumc** [comic/evalutils#321]
* evalutils version: 0.3.0
* Python version: 3.7, 3.8, 3.9
* Operating System: Linux - Github env - guessing some kind of debian distro based on environment

### Description

What I did: push to remote
Github CI runs according to the .github/workflows/ci.yml file, but never ends (well, I stopped it after 3 hours, where it takes ~ 1 minute on my local machine, so theoretically I am assuming it is infinite, but I am not waiting around to find out ;)

### What I Did

```
Cmd: git push
Github GUI / Actions tab / Action just keeps running... and running... and running
```

**Comment by jmsmkn** [comment]
Do you have any logs?

**Comment by GabyRumc** [comment]
Debugged this and found it was down to the cmd `cat /dev/urandom`, which is never really an advisable thing to do as it is same as e.g. `cat /dev/zero` or `cat /dev/null` which are "kernel" devices which will just keep pumping out bytes as long as `cat` is reading them...

Solution: you really want to limit the number of bytes returned from the call to `/dev/urandom`. A clean way of doing this is e.g. via `dd if=/dev/urandom bs=32 count=1` to return 32 bytes and terminate there so the next command can run.

I replaced the call to `/dev/urandom` in the `test.sh` script with this which works nicely:

`VOLUME_SUFFIX=$(dd if=/dev/urandom bs=32 count=1 | md5sum | cut --delimiter=' ' --fields=1)`

**Comment by jmsmkn** [comment]
PR with that would be welcome

**Comment by GabyRumc** [comment]
> PR with that would be welcome

On its way :-) plus some other "nice-to-have" shell script fixes in there for the generated "build.sh" and "test.sh" files - I think I might pull them out into separate commits though - one commit for this issue specifically and another commit for an issue I will create re general shell script improvements for build.sh and test.sh, that way we keep things nice and clean and trackable.

I have already forked the comic/evalutils repo so will push to my fork then do a PR rom my fork to the main repo hopefully later today for you

**Comment by GabyRumc** [comment]
> Do you have any logs?

Yes but nothing to actually, simply no output as cmd `cat /dev/urandom` runs forever
