### ISSUE TITLE
Add popular metric Normalised Surface Distance in medical image segmentation

### ISSUE THREAD

**Issue by EdwardZhao1991** [comic/evalutils#332]
* evalutils version: 0.3.1
* Python version: 3.9
* Operating System: Ubuntu 20.04

### Description
Thanks for the great work!

Would it be possible to add this new segmentation metric:Normalised Surface Distance?
The code is publicly available here
http://medicaldecathlon.com/files/Surface_distance_based_measures.ipynb

### What I Did
N/A

**Comment by jmsmkn** [comment]
I'm going to close this as we do not have the resources to add it. However, if you made a PR and it came with documentation and tests we would be happy to review it. We cannot add the code you linked to there because as far as I can tell it does not have a license.
