### ISSUE TITLE
Add .dockerignore

### ISSUE THREAD

**Issue by kiranvaidhya** [comic/evalutils#335]
The `algorithm` and the `evaluation` templates could benefit from a `.dockerignore` file. This helps speed up local testing as the build context becomes too large if there's a big `.tar.gz` (from an exported container) or a `.git` folder with neural network weights committed through LFS. 

The `.dockerignore` file could comprise the following for starters:

```
test/
.git/
*.tar.gz
```

**Comment by jmsmkn** [comment]
👍 could you make a PR?
