### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by zloysmiertniy** [comic/evalutils#336]
* evalutils version: 0.3.1
* Python version: 3.10.4
* Operating System: Linux

### Description

Installed successfully but no executable appears

### What I Did

I did `pip install evalutils` and it seems like it installed and the packages are in site-packages

but when I type `evalutils` it says `evalutils: command not found`

Any advice?

**Comment by kiranvaidhya** [comment]
There's an ongoing pull request to add support for Python 3.10 (https://github.com/comic/evalutils/pull/334). Could be related. Could you try Python 3.9 or 3.8 if possible?

**Comment by zloysmiertniy** [comment]
Oh yes! thank you I installed python 3.9.12 and it worked
